# Generated by Django 5.1.3 on 2025-01-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('very_happy', models.CharField(default='#FFD700', max_length=7)),
                ('happy', models.CharField(default='#FFFF00', max_length=7)),
                ('neutral', models.CharField(default='#C0C0C0', max_length=7)),
                ('sad', models.CharField(default='#87CEEB', max_length=7)),
                ('very_sad', models.CharField(default='#1E90FF', max_length=7)),
            ],
        ),
    ]
