# Generated by Django 5.1.3 on 2025-02-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotioncolor',
            name='is_breathing',
            field=models.BooleanField(default=False),
        ),
    ]
