# Generated by Django 5.1.3 on 2025-02-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0002_emotioncolor_is_breathing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotioncolor',
            old_name='happy',
            new_name='relaxed',
        ),
        migrations.AddField(
            model_name='emotioncolor',
            name='neutral_threshold',
            field=models.IntegerField(default=40, max_length=3),
        ),
        migrations.AddField(
            model_name='emotioncolor',
            name='relaxed_threshold',
            field=models.IntegerField(default=50, max_length=3),
        ),
        migrations.AddField(
            model_name='emotioncolor',
            name='sad_threshold',
            field=models.IntegerField(default=30, max_length=3),
        ),
        migrations.AddField(
            model_name='emotioncolor',
            name='very_happy_threshold',
            field=models.IntegerField(default=70, max_length=3),
        ),
        migrations.AddField(
            model_name='emotioncolor',
            name='very_relaxed',
            field=models.CharField(default='#FFFF00', max_length=7),
        ),
        migrations.AddField(
            model_name='emotioncolor',
            name='very_relaxed_threshold',
            field=models.IntegerField(default=60, max_length=3),
        ),
        migrations.AddField(
            model_name='emotioncolor',
            name='very_sad_threshold',
            field=models.IntegerField(default=20, max_length=3),
        ),
    ]
